### ISSUE TITLE
installation turtor tutorials wrong ?

### ISSUE THREAD

**Issue by Colaplusice** [chubin/cheat.sh#119]
in readme.md  the installation tutorials is :
```
To install the client:
    curl https://cht.sh/:cht.sh > ~/bin/cht.sh
    chmod +x ~/bin/cht.sh
```
but i execute is wrong. And i think this should be. 
```
    curl https://cht.sh/:cht.sh > /usr/local/bin/cht.sh
    chmod +x /usr/local/bin/cht.sh
```

**Comment by caltlgin** [comment]
@Colaplusice what you suggest requires admin privileges. eg:

```bash
sudo curl https://cht.sh/:cht.sh > /usr/local/bin/cht.sh
chmod +x /usr/local/bin/cht.sh
```

This is how I install cht.sh, which doesn't require admin privileges:

```bash
mkdir -p ~/.bin
wget -q --show-progress https://cht.sh/:cht.sh -O ~/.bin/cht.sh
chmod +x ~/.bin/cht.sh
echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
```

Granted, neither way is right or wrong. Its really personal preference.

**Comment by Colaplusice** [comment]
if choose the second way. I think we should add this into tutorials, or it will cause a misleadings to someone
```
mkdir -p ~/.bin
...
echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
```

**Comment by chubin** [comment]
@caltlgin This
```
sudo curl https://cht.sh/:cht.sh > /usr/local/bin/cht.sh
```
is wrong. Here you will run curl with root privileges, but not the redirection `>` (that is done by the current shell).

You should use `tee` instead:
```
curl https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cht.sh
```

@Colaplusice 

A couple of suggestions:

1) You make `~/.bin` directory, but add `~/.local/bin` to PATH.
2) If you modify `PATH` in `~/.bashrc` you should check, if you already have this directory in it.
Otherwise you end up with many copies of `~/.local/bin` in `PATH` if you run nested shells (this happens quite often).

**Comment by chubin** [comment]
I've extended the documentation with a couple of examples.
@Colaplusice please check if it looks better to you now.
