### ISSUE TITLE
Include "More Information" section of tldr pages

### ISSUE THREAD

**Issue by jpmcb** [chubin/cheat.sh#146]
Use case:

When looking up information for ripgrep:
```
$ curl cheat.sh/rg
```
I received the following:
```
#
# ripgrep
#
# A fast command-line search tool.
#
# Recursively search the current directory for a regex pattern:
  rg pattern
# ...
```

Initially I thought that it would be beneficial to include installation information in the output as it's not immediately clear where or how to install the binary.

I opened this issue with the tldr-project as it is the source of the cheat.sh basic unix information: https://github.com/tldr-pages/tldr/issues/3115

I learned that including the installation information in the tldr-pages would be somewhat outside the scope of the tldr project. But, I found that most pages include a "More information" section that directs to the home page of the tool (with more information on installation).

For example, the tldr [page for ripgrep includes](https://github.com/tldr-pages/tldr/blob/f2b1446e6247d3e794ee6577dee0c867dfc9af26/pages/common/rg.md) the following section:
```
# ripgrep
A fast command-line search tool. More information: https://github.com/BurntSushi/ripgrep.

Recursively search the current directory for a regex pattern:
...
```

Is there a reason the "More information" section of tldr-pages is not included in cheat.sh results? 

As a user of cheat.sh, I would expect the "More information" section of the source tldr-pages to be included.

**Comment by chubin** [comment]
@jpmcb You are absolutely right!

First of all, answer to your question: "More information" lines are not removed or somehow eliminated from the output, they should be displayed as is. In the `rg` case, its cheat sheet was simply not up to date on the server (because of a minor bug I've just fixed), I've forced the update procedure and now the page looks like it should. The pages are being updated every hour.

It would be really great to have several features:

1. For each command, automatically generate information how it can be installed (depending on your distro, and if you use the command line client and not curl, even automatically show the info only related to your distro, because the client knows what distro do you use):

```
# To install in Debian/Ubuntu:
apt-get install ripgrep # -> /usr/bin/rg
```

this information could be derived automatically from `apt-file` or `yum provides`.

We even started working on that, and I hope that the initial version of that will be available in some foreseen future (at least for Debian).

2. For each command, recommend similar/related commands. We already did some initial preparations for that, e.g. we added a special section `see_also` in the `cheat.sheets` repository:

For example:

https://github.com/chubin/cheat.sheets/blob/master/see_also/apt-get

Using this mechanism, it would be possible to get the see also recommendations
at the bottom of the cheat sheet, something like:

```
# See also:
# apt, apt-cache, apt-get, apt-key, aptitude
```

but for that we need to implement some initial hyperlinks support first.

**Comment by jpmcb** [comment]
Thanks for the quick turn around and the thoughtful response on this! I'm seeing that fix on my end now. I'll go ahead and close this as my issue has been resolved.
