### ISSUE TITLE
Cheat.sh is down

### ISSUE THREAD

**Issue by sirluky** [chubin/cheat.sh#228]
https://cheat.sh/ is down.
![image](https://user-images.githubusercontent.com/38957065/89401701-f866e780-d715-11ea-8cc3-67cdd25ccbc7.png)

**Comment by chubin** [comment]
oops, sorry for that, test it now please

**Comment by Onepamopa** [comment]
If you need ddos protection, let me know :)

**Comment by user-xffdsjkh** [comment]
Hi there,
So how would you be able to protect me from ddos? I could use more help if
you are willing, able & not my neighbor doing this to me....long story and
private.

On Aug 5, 2020 8:00 AM, "Onepamopa" <notifications@github.com> wrote:

If you need ddos protection, let me know :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chubin/cheat.sh/issues/228#issuecomment-669244124>, or
unsubscribe

**Comment by Onepamopa** [comment]
> 
> 
> @Onepamopa thank you! Is it a sort of CDN?
> (I will close the issue, but the question is relevant)

Yes, it is, btw followed you @ twitter
If issue reopens - close it ;)
