### ISSUE TITLE
go learn page missing

### ISSUE THREAD

**Issue by LazzariPaolo** [chubin/cheat.sh#23]
The command: 
`curl cheat.sh/go/:learn `
returns 
Unknown topic

**Comment by chubin** [comment]
@LazzariPaolo Thank you for reporting! The problem is fixed, but please keep in mind that the other go pages come not from `:learn`, but from another repository. This page is not being split, because there are no chapters/parts in the original document that could be automatically recognized (compare it to `:learn` of Perl or Python for example).
