### ISSUE TITLE
Add a query for a random cheatsheet

### ISSUE THREAD

**Issue by pavelgar** [chubin/cheat.sh#240]
Could it be possible to add a query which returns a random cheatsheet?
For example `cheat.sh/random` or `cheat.sh/:random`.
This would be useful for example as a shell startup message.

**Comment by chubin** [comment]
Yes, a ver good idea. In this case it must be `/:random`, and it should be in each namespace then, like `/:list`.

Feel free to participate, Pavel. If you want to try to implement it, let me know. I will tell you in details then where this query could be implemented

**Comment by fedebuonco** [comment]
Hi, I am new to the world of GitHub and Contributing but, if Pavel is not going to do it, I can try.

**Comment by chubin** [comment]
You are welcome! If you need any help, just let me know

**Comment by fedebuonco** [comment]
Ok, so I looked at the code and I tought about adding a _get_random_page on adapter.py and then write the different implementations in every adapter. 

They will all more or less follow this approch :  
- Get the list of all available pages with the already implementd _get_list 
- Using random.choice() we select one
- We call _get_page again but using as the topic the new random topic we just selected.

The thing is that every _get_page in each adapter should firstly check if we have :random,
I was thinking using a similar check as the one in internal.py, checking for :list 
 ```   
if topic.endswith('/:list') or topic.lstrip('/') == ':list':
            return self._get_list_answer(topic)
```

It will be 
 ```   
if topic.endswith('/:random') or topic.lstrip('/') == ':random':
            return self._get_random_page(topic)
```
What do you think about it? 
Thank you

**Comment by chubin** [comment]
Yes, it looks fine to me. I am not sure if you really want to implement for each adapter, it should be sufficient to add it to the base class, and may be add some special cases implementations. But general approach is perfect. So let's start

**Comment by fedebuonco** [comment]
On second thought I'd rather identify a random query in the 
```
def get_answer_dict(self, topic, request_options=None) 
```
In routing.py, this is because then I have already access to the whole topic list indipendently of the adapter and so I could immediately identify all the available pages. 

For example if I query a `cheat.sh/go/:random` I could select all the already gathered path available with the `get_topics_list` and selecting only the ones starting with `/go` (Also leaving out :list as we don't want it as a possible random answer).

I took this decision as the other method was too trublesome to implement also thinking about the problem it looks like a "routing.py" related addition and not an "adapter.py" job. 

I would add a `def is_random_request(self,topic)` and a `def select_random_topic(self,topic):` in the `get_answer_dict(self, topic, request_options=None)`

Does this sound reasonable or it is more of a "quick fix" ?

**Comment by chubin** [comment]
I think that your approach in your PR is quite reasonable. I like it
