### ISSUE TITLE
Angular and React

### ISSUE THREAD

**Issue by lodenrogue** [chubin/cheat.sh#295]
Couldn't get any results when searching for angular and react

**Comment by chubin** [comment]
How your query does look like?

**Comment by lodenrogue** [comment]
cheat.sh/angular and cheat.sh/react

**Comment by chubin** [comment]
Ok, now I see; we don't have such cheat sheets at the moment (feel free to add them, and they will be gradually extended by users), but you can try to ask some questions about Angular and React:

```
$ curl cheat.sh/angular/form+to+json
```

**Comment by sentientmachine** [comment]
Weighing in: Angular and React are travelling away from the original thesis of this tool you can see on the main README.md: 
 `Concise, Fast, Comprehensive, Universal,Unobtrusive, Tutoring, Inconspicuous`.

Where do you draw the line on tech-names for cheatsheets off the beaten path?  Why don't we have names for "Zune", "Dell computers" "Excel 1997", or god forbid: "Microsoft"?  If you go adding React and Angular, then the next people making tickets are going task why isn't there a named item for Tableau, MongoDB, and MeteorJS.

**Comment by lodenrogue** [comment]
Or just add them all.

**Comment by chubin** [comment]
As always, very good question Eric; I asked myself this question many times, and still didn't come to a final conclusion. Originally, the idea was to cover programming languages (and cli tools, of course), but it quickly became more than that.

For example, pretty early Redis and PostgreSQL cheat sheets were added:

```
curl cheat.sh/redis/:list
cheat.sh/psql/:list
```

This is not programming languages, but not very far from them though.

I think that the because of its curlable and terminal oriented nature,
there is no danger that the service will become to GUI-biased.

I think that the best approach would be to put more energy into the topics
popular among our users.

That is how top 50 queries groups (by number of unique queries) look like:

```
python
bash
java
javascript
go
cpp
c
php
vim
linux
git
rust
lua
ruby
csharp
shell
typescript
docker
scala
r                            # These queries are generated by Eric alone :)
html
sql
curl
django
zsh
awk
sed
perl
node
mysql
tmux
latex
markdown
powershell
css
pandas
find
haskell
clojure
swift
kotlin
ansible
ssh
android
rails
ffmpeg
ubuntu
```

The queries are distributed by the Zipf's law.

Ok, we don't have `angular` (pl.95) and `react` (pl.61) in the top50,
but we have `html` and `css` instead.

(side thought: I think we should compare cheat.sh popularity list
with TIOBE and try to find some interesting pattern in it)

**Comment by sentientmachine** [comment]
An argument might be made to "use the same language sets stack-overflow defines".  r-language is a niche language, but its the path that masters degree level machine learning pure researchers take, and its self-managing auto-tuning machine learning models that auto-magically knows what to do (since they were made by data scientists for data Scientists), is second to none, even python pandas/numpy/matplotlib/scikitlearn.

R was designed specifically for Data Science, and it has plug and play machine learning packages that you can't find anywhere else.  I use it as little as possible, and pluck off features into other languages where possible. for example: http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html

**Comment by chubin** [comment]
(It was a joke about R, r is rather popular among cheat.sh users.)

I have the feeling that R is slowly getting pushed out of itniche
by Python and Julia. 5 years ago it was not so, but nowadays,
I have the feeling, Python took over the role of the main data science language.

Cool article; it would be great to convert it into a set of cheat sheets

**Comment by sentientmachine** [comment]
R is hard to use because its type system is just not there, like C.  A variable is just a pointer to memory, and there's no traceback, unless you import a 3rd party or roll your own.  R Language is infuriatingly different from every other language. However if you can get past all that, the payout is Fortran/C levels of blazing speed for the 60 lines of code doing gradient ascent on very large datasets.  Machine Learning boils down to linear algebra and matric multiplication which is heavy on CPU and L1 Cache.  Somehow R is able to go between 4 and 8 orders of magnitude faster than Python in narrow situations.
