### ISSUE TITLE
when mistyping, gives error of highload

### ISSUE THREAD

**Issue by greggawatt** [chubin/cheat.sh#40]
```
curl cht.sh/ruby/lamba
# Sorry, we are experiencing extremely highload now.
# We are working on the problem and hope to get it fixed soon.
# Please come back in several hours or try some other queries:
#
# For example:

 curl cht.sh/:list               to list available cheat sheets
 curl cht.sh/LANGUAGE/:list      to list available cheat sheets for LANGUAGE
 curl cht.sh/LANGUAGE/:learn     to learn the LANGUAGE
```

i misspelled lambda and it gave me that error. Seems like it should tell me i'm wrong instead

**Comment by chubin** [comment]
Because it's true :)
If it knows the answer, it returns it immediately, and if it does not (`lamba`), it should generate it first, and because of the high load that we are experiencing currently (the cheat.sh is extremely popular at the moment because of trending on github) there are high chances that the query will be terminated while being processed.

We are trying to increase our capacities so that the service would work even under such extremely high load as now, but it will take some time. So please just wait a little bit, and the problem should be gone

**Comment by greggawatt** [comment]
oh ok thanks!
